[package]
edition = "2024"
name = "uvi"
version = "0.1.1"
authors = ["kkettums"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
git2 = "0.19"
regex = "1.12.2"

